# Generated by Django 4.0.2 on 2022-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_grade_user_specialization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
