# Generated by Django 4.0.2 on 2022-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_fact1_user_fact2_user_fact3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="grade",
            field=models.CharField(
                choices=[
                    ("SENIOR", "Senior"),
                    ("MIDDLE", "Middle"),
                    ("JUNIOR", "Junior"),
                    ("N/A", "Null"),
                ],
                default="JUNIOR",
                max_length=10,
                verbose_name="Grade",
            ),
        ),
    ]
