# Generated by Django 4.0.2 on 2022-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('SENIOR', 'Senior'), ('MIDDLE', 'Middle'), ('JUNIOR', 'Junior'), ('NULL', 'Null')], default='JUNIOR', max_length=10, verbose_name='Grade'),
        ),
    ]
