# Generated by Django 4.0.2 on 2022-11-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelationship',
            name='introduced',
            field=models.BooleanField(default=False),
        ),
    ]
