# Generated by Django 4.0.2 on 2022-11-26 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_userrelationship_introduced"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="collected_departments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
