# Generated by Django 4.0.2 on 2022-11-25 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.BigIntegerField(default=0)),
                ("finished", models.DateTimeField(null=True)),
                ("points", models.IntegerField(default=0)),
                (
                    "game_type",
                    models.CharField(
                        choices=[("full-name", "Full Name"), ("mapping", "Mapping")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("try_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GameSession",
                "verbose_name_plural": "GameSession",
                "db_table": "game_sessions",
            },
        ),
    ]
