# Generated by Django 4.0.2 on 2022-11-26 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="finished",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
