# Generated by Django 4.0.2 on 2022-11-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_gamesession_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('full-name', 'Full Name'), ('mapping', 'Mapping'), ('excluding', 'Excluding')], max_length=10, null=True),
        ),
    ]
