# Generated by Django 4.0.2 on 2022-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_gamesession_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('full-name', 'Full Name'), ('mapping', 'Mapping'), ('excluding', 'Excluding'), ('swiper', 'Swiper')], max_length=10, null=True),
        ),
    ]
